# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Aprenda.py
description: Aprenda programação em Python, e mais do que isso, solucione diversos problemas de engenharia por meio de ferramentas computacionais.
github_username: fschuch
# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "fschuch/aprenda.py"

minimal_mistakes_skin: default
locate: pt-BR
timezone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

author:
  name: Aprenda.py, por Felipe Schuch
  email: "aprenda.py@outlook.com"

# OPTIONAL: override baseurl and url if using a custom domain
# Note: leave out the trailing / from this value.
url: "https://fschuch.github.io" # the base hostname & protocol for your site, e.g. http://example.com

###########################################################
#########  Special Instructions for baseurl ###############
#
#### Scenario One: If you do not have a Custom Domain #####
#    -  if you are not using a custom domain, the baseurl *must* be set to your repo name
#
####  Scenario Two: If you have a Custom Domain #####
# 1. If your domain does NOT have a subpath, this leave this value as ""
# 2. If your domain does have a subpath, you must preceed the value with a / and NOT have a / at the end.
#      For example:
#           "" is valid
#           "/blog"        is valid
#            "/blog/site/" is invalid  ( / at the end)
#            "/blog/site"  is valid
#            "blog/site"   is invalid  ( because doesn't begin with a /)
#
# 3. You must replace the parameter `baseurl` in _action_files/settings.ini with the same value as you set here but WITHOUT QUOTES.
#
baseurl: "/aprenda.py" # the subpath of your site, e.g. "/blog".

# Github and twitter are optional:
minima:
  social_links:
    instagram: aprenda.py
    github: fschuch

# Set this to true to get LaTeX math equation support
use_math: true

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true

# Set this to true to display image previews on home page, if they exist
show_image: false

# Set this to true to display tags on each post
show_tags: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

# This specifies what badges are turned on by default for notebook posts.
default_badges:
  github: true
  binder: true
  colab: true

# Everything below here should be left alone. Modifications may break fastpages
future: false
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache  - jekyll-feed
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 15
paginate_path: /page:num/

remote_theme: mmistakes/minimal-mistakes

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

author:
  name   : "Felipe N. Schuch"
  avatar : "/assets/images/schuch.jpg"
  bio    : "I'm a PhD Student working with CFD and STEM." #"Doutorando em Engenharia Mecânica, com ênfase em Fluidodinâmica Computacional. Entusiasta em código livre e no emprego de ferramentas computacionais na vida cotidiana. Praticante de Pilates."
  location : "Porto Alegre, Brazil"
  links:
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       url: "https://"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:felipe.schuch@edu.pucrs.br
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/fschuch"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fschuch"
    # - label: "Linkedin"
    #   icon: "fab fa-fw fa-linkedin"
    #   url: "https://www.linkedin.com/in/fschuch/"
    # - label: "ResearchGate"
    #   icon: "fab fa-fw fa-researchgate"
    #   url: "https://www.researchgate.net/profile/Felipe_Schuch2"
    # - label: "Orcid"
    #   icon: "fab fa-fw fa-orcid"
    #   url: "http://orcid.org/0000-0002-6140-0273"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/fschuch"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fschuch"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/aprenda.py"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
